server {
    listen 127.0.0.1:8080;
    server_name localhost;

    root /opt/digilock/apps/current;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store";
    }
}