include:
  file: trixie-minbase-ab.yaml

# Install your web app package during image build.
# Replace jellyfin with your own package name, or set a local .deb path.
packages:
  app: jellyfin
# local_app: ${@SRCROOT}/debs/myapp_1.0.0_arm64.deb

image:
  system_part_size: 1500M # Cage + wayland + chromium + deps
  name: digilock-kiosk-image

layer:
  app: digilock-kiosk
  extra: rpi-splash-screen

splash:
  image_path: ${@SRCROOT}/splash.tga

kiosk:
  port: 8096
