include:
  file: trixie-minbase-ab.yaml

image:
  system_part_size: 1500M # Cage + wayland + chromium + deps
  name: digilock-kiosk-image

layer:
  app: digilock-kiosk
  extra: rpi-splash-screen

splash:
  image_path: ${@SRCROOT}/splash.tga

kiosk:
  url: "http://localhost:8080"
