include:
  file: trixie-minbase-ab.yaml

image:
  system_part_size: 1500M # Cage + wayland + chromium + deps
  name: digilock-kiosk-image

layer:
  app: digilock-kiosk
  extra: rpi-splash-screen

splash:
  image_path: ${@SRCROOT}/splash.tga

kiosk:
  # 1) Test app package from Debian apt repository
  app_pkg: lighttpd

  # 2) Optional custom apt repository info (leave empty to use default repos)
  repo_url:
  repo_suite: stable
  repo_component: main

  # 3) Public key for that apt repository (stored in this repo)
  repo_key: ${@SRCROOT}/keyrings/digilock-kiosk-archive-keyring.asc

  # 4) Lighttpd default local URL and port
  port: 80
  url: http://localhost
